#!/bin/bash
# my-erp-plan Terminal Restart Script
# Generated by Genesis v1.1.0

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}================================${NC}"
echo -e "${BLUE}Terminal Restart Guide${NC}"
echo -e "${BLUE}================================${NC}"
echo ""
echo -e "Project: ${GREEN}my-erp-plan${NC}"
echo -e "Type: ${GREEN}SaaS Application${NC}"
echo ""

# Check current directory
CURRENT_DIR=$(pwd)
EXPECTED_DIR="/home/klatt42/projects/genesis-skills-test/my-erp-plan"

if [ "$CURRENT_DIR" != "$EXPECTED_DIR" ]; then
  echo -e "${YELLOW}Warning: Not in project directory${NC}"
  echo -e "Current: $CURRENT_DIR"
  echo -e "Expected: $EXPECTED_DIR"
  echo ""
  echo "Run: cd /home/klatt42/projects/genesis-skills-test/my-erp-plan"
  exit 1
fi

echo -e "${BLUE}[1/2] Checking Git Status...${NC}"
echo ""
git status
echo ""

echo -e "${BLUE}[2/2] Current Branch:${NC}"
git branch --show-current
echo ""

echo -e "${GREEN}================================${NC}"
echo -e "${GREEN}Setup Instructions${NC}"
echo -e "${GREEN}================================${NC}"
echo ""

echo -e "${BLUE}TAB 1 (WSL - System Commands)${NC}"
echo -e "  Status: ${GREEN}✓ Ready${NC}"
echo ""
echo -e "  Available commands:"
echo -e "    ${YELLOW}npm run dev${NC}     - Start development server"
echo -e "    ${YELLOW}npm install${NC}     - Install dependencies"
echo -e "    ${YELLOW}git status${NC}      - Check git status"
echo -e "    ${YELLOW}git add .${NC}       - Stage changes"
echo -e "    ${YELLOW}git commit${NC}      - Commit changes"
echo ""

echo -e "${BLUE}TAB 2 (Claude Code - AI Development)${NC}"
echo ""
echo -e "  Setup steps:"
echo -e "    1. ${YELLOW}cd ~/projects/genesis-skills-test/my-erp-plan${NC}"
echo -e "    2. ${YELLOW}claude init${NC}"
echo -e "    3. Paste the context recovery prompt below:"
echo ""
echo -e "${BLUE}────────────────────────────────────────────────────────${NC}"
cat << 'PROMPT'
Reload Genesis context for my-erp-plan.

This is a SaaS Application project using Genesis patterns.

Please:
1. Review .github/CLAUDE_CODE_REMINDER.md
2. Review GENESIS_QUICK_START.md
3. Review PROJECT_STATUS.md
4. Invoke genesis-core skill
5. Invoke genesis-saas-app skill
6. Resume from current position in PROJECT_STATUS.md

Ready to continue development.
PROMPT
echo -e "${BLUE}────────────────────────────────────────────────────────${NC}"
echo ""

echo -e "${GREEN}================================${NC}"
echo -e "${GREEN}Quick Reference${NC}"
echo -e "${GREEN}================================${NC}"
echo ""
echo -e "📁 Project Structure:"
echo -e "  • GENESIS_QUICK_START.md  - Project overview & recovery"
echo -e "  • PROJECT_STATUS.md       - Current state & progress"
echo -e "  • .github/CLAUDE_CODE_REMINDER.md - Auto context reminder"
echo ""
echo -e "🔧 Development:"
echo -e "  • Tab 1: System commands (git, npm, etc.)"
echo -e "  • Tab 2: Claude Code (AI development)"
echo ""
echo -e "⚡ Next Steps:"
echo -e "  1. Start dev server in Tab 1: ${YELLOW}npm run dev${NC}"
echo -e "  2. Initialize Claude Code in Tab 2: ${YELLOW}claude init${NC}"
echo -e "  3. Paste recovery prompt in Tab 2"
echo ""
echo -e "${GREEN}✓ Restart guide complete!${NC}"
echo ""
